export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const SUCCESSFUL_ORDER = 'SUCCESSFUL_ORDER';
export const FAILED_ORDER = 'FAILED_ORDER';
export const SUBMITTING_ORDER = 'SUBMITTING_ORDER';
export const INIT_ORDER = 'INIT_ORDER';

export const INIT_FETCH_ORDERS = 'INIT_FETCH_ORDERS';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const INIT_AUTH = 'INIT_AUTH';
export const VERIFIED_AUTH = 'VERIFIED_AUTH';
export const FAILED_AUTH = 'FAILED_AUTH';
export const LOGOUT_AUTH = 'LOGOUT_AUTH';
